INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (935, 'jobId', 'f_aA1Q0ls8H85WTbO990');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (936, 'jobId', 'gikfd0RlJE06AbWUidVJ');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (937, 'jobId', 'VrGd3VY4dy11IazCq1a6');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (938, 'jobId', 'cGqIeByU38ZmoEQloRfe');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (984, 'jobId', 'ZPi_bqFv0iO9WF0EozNB');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (985, 'jobId', 'i0rIgZf_OHn-hkKVRFTY');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1186, 'jobId', '1aVr_M2cO0418epZQfyL');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1187, 'jobId', 'Kie3V7i40Pcltudi8Gh-');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1188, 'jobId', 'RMCsScRMG7iPrTG8VPia');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1189, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1189, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1189, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1189, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1189, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1190, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1190, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1190, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1190, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1190, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1191, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1191, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1191, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1191, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1191, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1192, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1192, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1192, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1192, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1192, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1193, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1193, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1193, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1193, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1193, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1194, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1194, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1194, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1194, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1194, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1195, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1195, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1195, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1195, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1195, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1196, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1196, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1196, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1196, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1196, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1197, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1197, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1197, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1197, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1197, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1198, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1198, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1198, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1198, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1198, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1199, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1199, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1199, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1199, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1199, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1200, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1200, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1200, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1200, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1200, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1201, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1201, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1201, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1201, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1201, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1202, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1202, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1202, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1202, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1202, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1203, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1203, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1203, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1203, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1203, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1204, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1204, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1204, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1204, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1204, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1205, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1205, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1205, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1205, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1205, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1206, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1206, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1206, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1206, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1206, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1207, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1207, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1207, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1207, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1207, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1208, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1208, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1208, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1208, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1208, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1209, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1209, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1209, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1209, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1209, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1210, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1210, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1210, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1210, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1210, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1211, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1211, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1211, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1211, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1211, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1212, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1212, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1212, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1212, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1212, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1213, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1213, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1213, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1213, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1213, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1214, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1214, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1214, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1214, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1214, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1215, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1215, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1215, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1215, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1215, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1216, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1216, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1216, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1216, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1216, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1217, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1217, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1217, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1217, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1217, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1218, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1218, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1218, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1218, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1218, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1219, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1219, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1219, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1219, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1219, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1220, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1220, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1220, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1220, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1220, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1221, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1221, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1221, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1221, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1221, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1222, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1222, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1222, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1222, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1222, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1223, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1223, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1223, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1223, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1223, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1224, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1224, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1224, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1224, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1224, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1225, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1225, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1225, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1225, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1225, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1226, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1226, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1226, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1226, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1226, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1227, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1227, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1227, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1227, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1227, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1228, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1228, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1228, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1228, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1228, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1229, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1229, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1229, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1229, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1229, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1230, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1230, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1230, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1230, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1230, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1231, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1231, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1231, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1231, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1231, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1232, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1232, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1232, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1232, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1232, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1233, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1233, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1233, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1233, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1233, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1234, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1234, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1234, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1234, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1234, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1235, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1235, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1235, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1235, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1235, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1236, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1236, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1236, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1236, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1236, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1237, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1237, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1237, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1237, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1237, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1238, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1238, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1238, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1238, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1238, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1239, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1239, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1239, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1239, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1239, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1240, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1240, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1240, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1240, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1240, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1241, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1241, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1241, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1241, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1241, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1242, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1242, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1242, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1242, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1242, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1243, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1243, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1243, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1243, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1243, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1244, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1244, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1244, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1244, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1244, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1245, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1245, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1245, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1245, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1245, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1246, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1246, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1246, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1246, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1246, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1247, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1247, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1247, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1247, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1247, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1248, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1248, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1248, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1248, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1248, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1249, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1249, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1249, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1249, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1249, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1250, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1250, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1250, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1250, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1250, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1251, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1251, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1251, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1251, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1251, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1252, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1252, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1252, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1252, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1252, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1253, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1253, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1253, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1253, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1253, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1254, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1254, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1254, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1254, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1254, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1255, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1255, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1255, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1255, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1255, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1256, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1256, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1256, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1256, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1256, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1257, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1257, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1257, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1257, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1257, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1258, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1258, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1258, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1258, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1258, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1259, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1259, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1259, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1259, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1259, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1260, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1260, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1260, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1260, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1260, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1261, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1261, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1261, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1261, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1261, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1262, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1262, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1262, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1262, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1262, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1263, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1263, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1263, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1263, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1263, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1264, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1264, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1264, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1264, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1264, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1265, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1265, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1265, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1265, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1265, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1266, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1266, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1266, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1266, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1266, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1267, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1267, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1267, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1267, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1267, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1268, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1268, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1268, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1268, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1268, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1269, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1269, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1269, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1269, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1269, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1270, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1270, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1270, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1270, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1270, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1271, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1271, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1271, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1271, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1271, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1272, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1272, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1272, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1272, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1272, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1273, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1273, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1273, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1273, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1273, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1274, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1274, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1274, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1274, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1274, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1275, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1275, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1275, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1275, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1275, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1276, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1276, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1276, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1276, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1276, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1277, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1277, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1277, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1277, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1277, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1278, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1278, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1278, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1278, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1278, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1279, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1279, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1279, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1279, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1279, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1280, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1280, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1280, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1280, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1280, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1281, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1281, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1281, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1281, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1281, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1282, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1282, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1282, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1282, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1282, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1283, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1283, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1283, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1283, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1283, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1284, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1284, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1284, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1284, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1284, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1285, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1285, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1285, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1285, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1285, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1286, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1286, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1286, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1286, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1286, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1287, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1287, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1287, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1287, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1287, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1288, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1288, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1288, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1288, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1288, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1289, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1289, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1289, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1289, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1289, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1290, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1290, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1290, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1290, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1290, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1291, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1291, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1291, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1291, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1291, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1292, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1292, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1292, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1292, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1292, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1293, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1293, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1293, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1293, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1293, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1294, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1294, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1294, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1294, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1294, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1295, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1295, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1295, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1295, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1295, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1296, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1296, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1296, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1296, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1296, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1297, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1297, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1297, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1297, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1297, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1298, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1298, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1298, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1298, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1298, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1299, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1299, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1299, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1299, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1299, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1300, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1300, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1300, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1300, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1300, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1301, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1301, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1301, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1301, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1301, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1302, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1302, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1302, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1302, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1302, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1303, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1303, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1303, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1303, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1303, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1304, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1304, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1304, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1304, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1304, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1305, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1305, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1305, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1305, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1305, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1306, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1306, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1306, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1306, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1306, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1307, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1307, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1307, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1307, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1307, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (1961, 'jobId', 'dEJ9pWp5oBNhed3su6px');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (2059, 'jobId', 'Ro3dgh4_C1zkvTlMsnt4');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (2154, 'jobId', 'sAxPtfTCLy7gqf3IjQR3');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (2263, 'jobId', '-Z7XQ6dkIV1aJlBCUhQj');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (2268, 'jobId', 'OyVZo7CvWe_GeXXUNoBM');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (2273, 'jobId', 'KRW6kHPU_J7CscpkIk7C');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (2274, 'jobId', '79ZCG9BO7Zf6YZmCR__0');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (2275, 'jobId', 'LjquVDBF7sGRL2M_veG-');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (2276, 'jobId', 'p0F-FBAEQhUVP9pThNhJ');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (2277, 'jobId', 'Jky3kqcOUW5lpd7OI2RC');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (2278, 'jobId', 'KbrUPKIWo7CGEABsSNh1');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5061, 'jobId', 'KRW6kHPU_J7CscpkIk7C');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5062, 'jobId', '79ZCG9BO7Zf6YZmCR__0');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5063, 'jobId', 'LjquVDBF7sGRL2M_veG-');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5064, 'jobId', 'p0F-FBAEQhUVP9pThNhJ');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5065, 'jobId', 'Jky3kqcOUW5lpd7OI2RC');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5066, 'jobId', '-Z7XQ6dkIV1aJlBCUhQj');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5067, 'jobId', 'dEJ9pWp5oBNhed3su6px');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5068, 'jobId', 'sAxPtfTCLy7gqf3IjQR3');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5072, 'jobId', 'KbrUPKIWo7CGEABsSNh1');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5073, 'jobId', 'f_aA1Q0ls8H85WTbO990');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5074, 'jobId', 'gikfd0RlJE06AbWUidVJ');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5075, 'jobId', 'VrGd3VY4dy11IazCq1a6');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5076, 'jobId', 'cGqIeByU38ZmoEQloRfe');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5835, 'jobId', 'ZPi_bqFv0iO9WF0EozNB');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5836, 'jobId', 'i0rIgZf_OHn-hkKVRFTY');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5859, 'jobId', 'Ro3dgh4_C1zkvTlMsnt4');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5861, 'jobId', '1aVr_M2cO0418epZQfyL');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5863, 'jobId', 'Kie3V7i40Pcltudi8Gh-');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (5866, 'jobId', 'OyVZo7CvWe_GeXXUNoBM');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6463, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6463, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6463, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6463, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6463, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6464, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6464, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6464, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6464, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6464, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6465, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6465, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6465, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6465, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6465, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6466, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6466, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6466, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6466, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6466, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6467, 'city', 'West Kingsdown');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6467, 'country', 'UK');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6467, 'countryCode', 'GBR');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6467, 'location', 'Revolve 24 Brands Hatch');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6467, 'provinceState', 'Kent');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6525, 'jobId', 'KRW6kHPU_J7CscpkIk7C');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6526, 'jobId', '79ZCG9BO7Zf6YZmCR__0');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6527, 'jobId', 'LjquVDBF7sGRL2M_veG-');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6528, 'jobId', 'p0F-FBAEQhUVP9pThNhJ');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6529, 'jobId', 'Jky3kqcOUW5lpd7OI2RC');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6530, 'jobId', '-Z7XQ6dkIV1aJlBCUhQj');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6531, 'jobId', 'dEJ9pWp5oBNhed3su6px');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6532, 'jobId', 'sAxPtfTCLy7gqf3IjQR3');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6536, 'jobId', 'KbrUPKIWo7CGEABsSNh1');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6537, 'jobId', 'f_aA1Q0ls8H85WTbO990');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6538, 'jobId', 'gikfd0RlJE06AbWUidVJ');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6539, 'jobId', 'VrGd3VY4dy11IazCq1a6');
INSERT INTO digikam.ImageProperties (imageid, property, value) VALUES (6540, 'jobId', 'cGqIeByU38ZmoEQloRfe');
