INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (0, -1, '_Digikam_root_tag_', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (1, 0, '_Digikam_Internal_Tags_', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (2, 1, 'Current Version', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (3, 1, 'Version Always Visible', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (4, 0, 'people', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (5, 4, 'Unknown', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (6, 1, 'Need Resolving History', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (7, 1, 'Need Tagging History Graph', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (8, 1, 'Color Label None', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (9, 1, 'Color Label Red', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (10, 1, 'Color Label Orange', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (11, 1, 'Color Label Yellow', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (12, 1, 'Color Label Green', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (13, 1, 'Color Label Blue', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (14, 1, 'Color Label Magenta', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (15, 1, 'Color Label Gray', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (16, 1, 'Color Label Black', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (17, 1, 'Color Label White', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (18, 1, 'Pick Label None', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (19, 1, 'Pick Label Rejected', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (20, 1, 'Pick Label Pending', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (21, 1, 'Pick Label Accepted', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (22, 0, '2019, Sussex Sport Photography, revolve24, brands hatch, bike, endurance, track, cycle, 24hr, 12hr, 6hr', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (23, 4, 'Unconfirmed', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (24, 4, 'Ignored', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (25, 0, '2009', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (26, 0, '2010', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (27, 0, '2011', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (28, 0, '2012', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (29, 0, 'sport', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (30, 0, 'event', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (31, 0, 'holiday', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (32, 0, 'football', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (33, 0, '2013', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (34, 0, '2014', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (35, 0, '2015', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (36, 0, '2017', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (37, 0, '2018', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (38, 0, '2019', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (39, 0, 'wedding', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (40, 0, 'cycling', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (41, 0, '2020', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (42, 0, 'docosoft', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (43, 0, '2021', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (44, 0, 'college', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (45, 0, 'protests', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (46, 0, 'family', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (47, 0, 'zendesk', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (48, 0, 'the-lads', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (49, 4, 'eoin-farrell', 532, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (50, 0, '2016', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (53, 31, 'poznan', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (54, 31, 'achill-2020', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (55, 31, 'america-2017', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (56, 31, 'japan', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (57, 31, 'gran-canaria', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (58, 0, 'video', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (59, 0, '2022', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (60, 1, 'Original Version', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (62, 31, 'galway', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (63, 31, 'brighton-2018', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (64, 0, 'Christmas', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (65, 1, 'Scanned for Faces', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (66, 4, 'john-lennon', 516, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (67, 4, 'shane-farrell', 525, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (68, 4, 'harry-stephenson', 2150, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (69, 4, 'john-paul-quill', 535, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (70, 4, 'garreth-kelly', 532, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (71, 4, 'ciaran-hegarty', 5104, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (72, 4, 'richard-bridge', 5104, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (73, 4, 'adam-ward', 5104, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (75, 4, 'emmet-burke', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (76, 4, 'pepsi', 5140, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (77, 4, 'amy-farrell', 5144, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (78, 4, 'conor-farrell', 5145, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (79, 4, 'brian-mcdonald', 5174, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (80, 4, 'dennis-cummins', 6404, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (81, 4, 'donal-farrell', 6460, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (82, 4, 'david-geraghty', 6491, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (83, 0, 'private', null, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (84, 4, 'lily-farrell', 6501, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (85, 4, 'ian-gobl', 6645, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (86, 4, 'patrick-buckley', 6646, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (87, 4, 'paul-jordan', 6646, null);
INSERT INTO digikam.Tags (id, pid, name, icon, iconkde) VALUES (88, 31, 'dublin-to-newry', null, null);
